name: deploy

on:
  push:
    branches:
      - '*'
    ignore-paths:
      - 'REPO'
      - '*.md'
      - '*.httpup'
      - '.httpup-repgen-ignore'
      - '.github/workflows/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    #continue-on-error: true
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      - name: Download and prepare httpup-repgen
        run: |
          cd /tmp
          wget -q https://crux.nu/files/httpup-0.5.0.tar.xz
          tar xf httpup-0.5.0.tar.xz httpup-0.5.0/httpup-repgen

      - name: Update REPO file
        run: |
          /tmp/httpup-0.5.0/httpup-repgen
          cat REPO

      - name: Push to remote
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git add REPO
          git commit -m "Update REPO file" REPO
          bash -c "[[ $(git diff -r HEAD | wc -l) = 0 ]] || git push"
